name: CI-SAMPLE-TST
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      testExecKey: 
        description: 'Test firstcry App'
        default: 'https://jdeesh123.atlassian.net/browse/TES-63'
        required: true
      projectKey:
        description: 'Test firstcry App'
        default: 'https://jdeesh123.atlassian.net/jira/software/c/projects/TES/boards/2'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
        - uses: szenius/set-timezone@v1.1
          with:
            timezoneLinux: "America/New_York"
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test    
          run: npm run test:browserstack.first.tst:linux
        - name: "Import results to Xray"
          uses: mikepenz/xray-action@v3.0.4
          with:
            username: 07C307CA10C041D38DB399C56E1A1EDA
            password: b8b00b1d4839d43c8e7c90060ff2e5d49c93eba268693dc5342451a8de4da8df
            testFormat: "junit"
            testPaths: "**/test/*.xml"
            testExecKey: "TES-63"
            projectKey: "ClientProject-1"