name: CI-SAMPLE-TST
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      testExecKey: 
        description: 'Test firstcry App'
        default: ''
        required: true
      projectKey:
        description: 'Test firstcry App'
        default: ''
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
        - uses: szenius/set-timezone@v1.1
          with:
            timezoneLinux: "America/New_York"
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          env:
            USERNAME: ${{ secrets.JIRA_USERNAME }}
            PASSWORD: ${{ secrets.JIRA_PASSWORD }}
            XRAY_CLOUD: "false"
            XRAY_BASE_URL: ${{ secrets.JIRA_BASEURL }}
            TEST_FORMAT: "junit"
            TEST_PATHS: "**/xray-report.xml"
            TEST_PLAN_KEY: "${{ secrets.JIRA_TEST_PLAN_KEY }}"
            PROJECT_KEY: "${{ secrets.JIRA_PROJECT_KEY }}"
            TEST_ENVIRONMENTS: "NODE_${{ matrix.node-version }}"
          run: npm run test:browserstack.first.tst:linux
        - uses: actions/upload-artifact@v1
          continue-on-error: true
          if: failure()
          with:
            name: logs
            path: logs
