name: CI-SAMPLE-TST
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      testExecKey: 
        description: 'Test firstcry App'
        default: 'https://jdeesh123.atlassian.net/browse/TES-63'
        required: true
      projectKey:
        description: 'Test firstcry App'
        default: 'https://jdeesh123.atlassian.net/jira/software/c/projects/TES/boards/2'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
        - uses: szenius/set-timezone@v1.1
          with:
            timezoneLinux: "America/New_York"
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          env:
            USERNAME: jega deesh
            PASSWORD: Jegadeesh123@
            XRAY_CLOUD: "false"
            XRAY_BASE_URL: https://jdeesh123.atlassian.net/
            TEST_PATHS: "**/xray-report.xml"
            TEST_PLAN_KEY: "https://jdeesh123.atlassian.net/browse/TES-63"
            PROJECT_KEY: "https://jdeesh123.atlassian.net/jira/software/c/projects/TES/boards/2"
            TEST_ENVIRONMENTS: "NODE_${{ matrix.node-version }}"
          run: npm run test:browserstack.first.tst:linux
        - name: xray-action
          uses: mikepenz/xray-action@v3.0.4
